### PR TITLE
Add comment to rule

### PR DESCRIPTION
**Pull request by wooparadog**

### CODE REVIEW

**Comment by hit9** [comment]
Nice

**Comment by hit9** [comment]
Branch outdated

**Comment by wooparadog** [comment]
@hit9 I have no idea how to do a db migration, maybe it's automatic?

**Comment by hit9** [comment]
yep. Auto migrating...

**Comment by wooparadog** [comment]
It's fxking awesome.

**Comment by hit9** [comment]
Need add rule to alerting message.

**Pull request merged**
